### ISSUE TITLE
（建议）横向滚动条始终显示在视口内功能

### ISSUE THREAD

**Issue by brightlight2017** [JdesHZ/el-table-bar#2]
背景：使用Element UI table，内容超过一屏，且出现横向滚动条时，如果想看右边的列，需要先把竖向滚动条拉到下面，然后拖动横向滚动条到右边，再把竖向滚动条拉上去，非常不方便。

建议：表格内容超过一屏时，横向滚动条固定在窗口底部，向下拖动竖向滚动条，表格底部出现在视口内时，横向滚动条复位到表格底部。

这个方案应该能解决很多人的痛点，😁。

我按照这个方法结合自己的业务通过定位切换处理了一下，如果能组件层面解决，我觉得会更好。

**Comment by brightlight2017** [comment]
![1](https://user-images.githubusercontent.com/28212171/58780704-537de580-860c-11e9-95bc-17769473fca7.png)
![2](https://user-images.githubusercontent.com/28212171/58780712-5aa4f380-860c-11e9-9d3a-b33c5aee088c.png)
图一是表格内容超过一屏时横向滚动条固定在窗口下部
图二是表格底部在视口内，横向滚动条复位到表格底部

**Comment by JdesEva** [comment]
嗯，多谢提议，我思考一下该怎么写😂毕竟这一开始只是基于elscrollbar做了一次封装😂



发自我的小米手机
在 suchenglin2017 <notifications@github.com>，2019年6月3日 14:19写道：

背景：使用Element UI table，内容超过一屏，且出现横向滚动条时，如果想看右边的列，需要先把竖向滚动条拉到下面，然后拖动横向滚动条到右边，再把竖向滚动条拉上去，非常不方便。

建议：表格内容超过一屏时，横向滚动条固定在窗口底部，向下拖动竖向滚动条，表格底部出现在视口内时，横向滚动条复位到表格底部。

这个方案应该能解决很多人的痛点，😁。

我按照这个方法结合自己的业务通过定位切换处理了一下，如果能组件层面解决，我觉得会更好。

**Comment by JdesEva** [comment]
> 背景：使用Element UI table，内容超过一屏，且出现横向滚动条时，如果想看右边的列，需要先把竖向滚动条拉到下面，然后拖动横向滚动条到右边，再把竖向滚动条拉上去，非常不方便。
> 
> 建议：表格内容超过一屏时，横向滚动条固定在窗口底部，向下拖动竖向滚动条，表格底部出现在视口内时，横向滚动条复位到表格底部。
> 
> 这个方案应该能解决很多人的痛点，😁。
> 
> 我按照这个方法结合自己的业务通过定位切换处理了一下，如果能组件层面解决，我觉得会更好。

大概看了一下，是可以通过定位问题解决，但是需要考虑并列表格的情况，我先思考一下。会尽快给出解决办法。感谢提议~

**Comment by JdesEva** [comment]
大体功能已经实现，目前还有两个问题还未解决，解决之后通过测试就会发布的



发自我的小米手机在 suchenglin2017 <notifications@github.com>，2019年6月3日 14:33写道：



图一是表格内容超过一屏时横向滚动条固定在窗口下部

图二是表格底部在视口内，横向滚动条复位到表格底部



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/JdesHZ/el-table-bar-base/issues/2?email_source=notifications\u0026email_token=AI4B7MLCYFGHL5Y7P26VWCLPYS3LPA5CNFSM4HSE5T72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWYN25I#issuecomment-498130293",

"url": "https://github.com/JdesHZ/el-table-bar-base/issues/2?email_source=notifications\u0026email_token=AI4B7MLCYFGHL5Y7P26VWCLPYS3LPA5CNFSM4HSE5T72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWYN25I#issuecomment-498130293",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by JdesEva** [comment]
> ![1](https://user-images.githubusercontent.com/28212171/58780704-537de580-860c-11e9-95bc-17769473fca7.png)
> ![2](https://user-images.githubusercontent.com/28212171/58780712-5aa4f380-860c-11e9-9d3a-b33c5aee088c.png)
> 图一是表格内容超过一屏时横向滚动条固定在窗口下部
> 图二是表格底部在视口内，横向滚动条复位到表格底部

功能完成啦，代码也已经推送，npm也已经发布测试版本包，使用 npm i  el-table-bar@2.0.0-beta 即可下载，欢迎提出新的问题

**Comment by brightlight2017** [comment]
安装了 "el-table-bar-base": "^2.0.0-beta",el-table-bar标签上也加上了fixed，但滚动条一直在表格底部，没有浮动。
试了你的例子，没有问题。
我的数据是接口返回的，会不会是这个原因没有浮动在窗口底部呢？

**Comment by brightlight2017** [comment]
在updated钩子里再绑定一遍页面监听试试？

**Comment by JdesEva** [comment]
> 在updated钩子里再绑定一遍页面监听试试？

页面监听并不是触发在 生命周期里面。因为考虑到页面大小改变的情况，实际的页面监听是 mouseEnter 、还有鼠标滚轮的wheel事件（当然两个都有节流优化）。你说的情况我这边再测试一下。

**Comment by JdesEva** [comment]
> 安装了 "el-table-bar-base": "^2.0.0-beta",el-table-bar标签上也加上了fixed，但滚动条一直在表格底部，没有浮动。
> 试了你的例子，没有问题。
> 我的数据是接口返回的，会不会是这个原因没有浮动在窗口底部呢？

个人疏漏了，当时考虑到性能原因，有两个属性获取写在了mounted钩子里，忘了数据更新情况，现在demo也是异步的情况了，npm已经更新 2.0.1-beta 更新之后就行了

**Comment by brightlight2017** [comment]
现在还有个小问题，表格宽度是够的，正常情况是不应该出现横向滚动条的，但出现了滚动条，并且拖不动，我还没看出来哪个地方的原因。

**Comment by JdesEva** [comment]
我大概知道哪里，是由 有滚动条的小窗口状态切换到最大化的时候，在最大化窗口下出现的吗？



发自我的小米手机在 suchenglin2017 <notifications@github.com>，2019年6月4日 18:15写道：现在还有个小问题，表格宽度是够的，正常情况是不应该出现横向滚动条的，但出现了滚动条，并且拖不动，我还没看出来哪个地方的原因。



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/JdesHZ/el-table-bar-base/issues/2?email_source=notifications\u0026email_token=AI4B7MIKXJUENNANOIYORHDPYY6ERA5CNFSM4HSE5T72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4DJRA#issuecomment-498611396",

"url": "https://github.com/JdesHZ/el-table-bar-base/issues/2?email_source=notifications\u0026email_token=AI4B7MIKXJUENNANOIYORHDPYY6ERA5CNFSM4HSE5T72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4DJRA#issuecomment-498611396",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by brightlight2017** [comment]
![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。

**Comment by brightlight2017** [comment]
不加fixed属性时，超出宽度的表格横向滚动条没有出现。
![4](https://user-images.githubusercontent.com/28212171/58923825-de2d2480-8773-11e9-919b-98f8e83bba02.png)

**Comment by brightlight2017** [comment]
> ![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
> 不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。

这个问题，_map函数中判断一下如果this.isScrollBar为假，scroll.style.width = 0% 应该就好了

**Comment by JdesEva** [comment]
> > ![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
> > 不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。
> 
> 这个问题，_map函数中判断一下如果this.isScrollBar为假，scroll.style.width = 0% 应该就好了

大体是设置 scroll.style.width = 0 这个解决办法，但不是在 this.isScrollBar  = false 这个条件。问题已经修复。代码也进行了相应的优化并已经推送。正式版本已经更新至 npm 。欢迎再次指正问题

**Comment by brightlight2017** [comment]
example示例在IE11下没有出现内容，😅

**Comment by JdesEva** [comment]
> example示例在IE11下没有出现内容，😅

IE11我测试过了，可以的啊。

**Comment by brightlight2017** [comment]
你那没问题就行了，我的IE出问题了，回头我重装看看😁

**Comment by JdesEva** [comment]
> 你那没问题就行了，我的IE出问题了，回头我重装看看😁

没问题的话。这条issue我就关了哈

**Comment by ChasonHong** [comment]
> > > ![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
> > > 不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。
> > 
> > 
> > 这个问题，_map函数中判断一下如果this.isScrollBar为假，scroll.style.width = 0% 应该就好了
> 
> 大体是设置 scroll.style.width = 0 这个解决办法，但不是在 this.isScrollBar = false 这个条件。问题已经修复。代码也进行了相应的优化并已经推送。正式版本已经更新至 npm 。欢迎再次指正问题

这个问题最新版本依然存在 @JdesEva

**Comment by JdesEva** [comment]
> > > > ![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
> > > > 不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。
> > > 
> > > 
> > > 这个问题，_map函数中判断一下如果this.isScrollBar为假，scroll.style.width = 0% 应该就好了
> > 
> > 
> > 大体是设置 scroll.style.width = 0 这个解决办法，但不是在 this.isScrollBar = false 这个条件。问题已经修复。代码也进行了相应的优化并已经推送。正式版本已经更新至 npm 。欢迎再次指正问题
> 
> 这个问题最新版本依然存在 @JdesEva

已知晓，感谢指出问题

**Comment by JdesEva** [comment]
> > > > > ![3](https://user-images.githubusercontent.com/28212171/58886384-61b82880-8716-11e9-9809-37fa019225a8.png)
> > > > > 不是切换窗口时，正常状态下，宽度足够的表格，鼠标放上，会出现不能拖动的横向滚动条，我记得上个版本如果宽度足够，即使鼠标放入表格，也不会出现横向滚动条。
> > > > 
> > > > 
> > > > 这个问题，_map函数中判断一下如果this.isScrollBar为假，scroll.style.width = 0% 应该就好了
> > > 
> > > 
> > > 大体是设置 scroll.style.width = 0 这个解决办法，但不是在 this.isScrollBar = false 这个条件。问题已经修复。代码也进行了相应的优化并已经推送。正式版本已经更新至 npm 。欢迎再次指正问题
> > 
> > 
> > 这个问题最新版本依然存在 @JdesEva
> 
> 已知晓，感谢指出问题

已修复此问题，原因在于判断滚动条时候乘以了一个滚动条的粘滞系数（0.99-0.992），在判断时漏乘了该系数。已经发布2.1.3版本，更新版本即可

**Comment by zw1990** [comment]
fixed 和native能不能兼容一下呢，就是设置固定列的情况横向滚动条也能固定在窗口底部

**Comment by JdesEva** [comment]
> fixed 和native能不能兼容一下呢，就是设置固定列的情况横向滚动条也能固定在窗口底部

此想法在native属性出现之前就进行过尝试，无法实现。

**Comment by Eric-kbo** [comment]
使用这个组件的时候，需要怎么配置吗？我把 el-table-bar 套在了我的table外面，结果滚动条没有了，不知道怎么让他展示出来了，有模板代码吗？

**Comment by Eric-kbo** [comment]
我找到问题了，原来我在下面加了一个分页的浮动，挡住了组件的滚动条
![企业微信截图_16037888715107](https://user-images.githubusercontent.com/21054873/97278781-22dbc300-1875-11eb-94d1-962b7d2761bb.png)
![企业微信截图_16037889261084](https://user-images.githubusercontent.com/21054873/97278857-3850ed00-1875-11eb-80ff-fc583fe2f557.png)

**Comment by Eric-kbo** [comment]
分页是否可以加入到这个组件当中呢？像滚动条一样吸底

**Comment by Eric-kbo** [comment]
还有个问题就是没有表头吸顶，自己加上表头吸顶的话，table-bar在滚动的时候会识别不到

**Comment by Eric-kbo** [comment]
![企业微信截图_16037900018156](https://user-images.githubusercontent.com/21054873/97280993-ecec0e00-1877-11eb-8da5-014a99dee7fe.png)

**Comment by JdesEva** [comment]
> 还有个问题就是没有表头吸顶，自己加上表头吸顶的话，table-bar在滚动的时候会识别不到

表头吸顶实际上和 elementui Table 的 fixed 属性是一样的问题，在设计之初就考虑过这个问题，由于 elementui Table 的设计问题，该功能并不能实现，强行使用是会出问题的。
